[package]
name = "bluez-async-ots"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["cli"]

[dependencies]
anyhow = "1"
uuid = "1"
libc = "0.2"
socket2 = "0.5"

[dependencies.log]
version = "0.4"

[dependencies.futures]
version = "0.3"

[dependencies.bytemuck]
version = "1"
features = ["derive"]

[dependencies.bitflags]
version = "2"
features = ["bytemuck"]

[dependencies.bluez-async]
version = "0.7"

#[dependencies.bluer]
#version = "0.16"
#default-features = false
#features = ["l2cap"]

[dependencies.tokio]
version = "1"
default-features = false
features = ["time", "io-util"]
