name: Rust
on:
  push:
    branches:
      - master
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
  pull_request:

jobs:
  format:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: nightly
          components: rustfmt
      - uses: Swatinem/rust-cache@v2
      - name: Format
        run: cargo fmt --all -- --check

  doc:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: nightly
          components: rust-docs
      - uses: Swatinem/rust-cache@v2
      - name: Install system dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y --install-recommends libdbus-1-dev
      - name: Documentation
        env:
          DOCS_RS: 1
        run: cargo doc --all --all-features

  check:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: nightly
          components: clippy
      - uses: Swatinem/rust-cache@v2
      - name: Install system dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y --install-recommends libdbus-1-dev
      - uses: sksat/action-clippy@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-check
          fail_on_error: true
          clippy_flags: --all --all-targets --all-features

  # minver:
  #   runs-on: ubuntu-20.04
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: dtolnay/rust-toolchain@v1
  #       with:
  #         toolchain: nightly
  #     - uses: Swatinem/rust-cache@v2
  #     - run: cargo check --all --all-features --all-targets -Z minimal-versions

  test:
    needs:
      - format
      - doc
      - check
    strategy:
      fail-fast: ${{ startsWith(github.ref, 'refs/tags/') }}
      matrix:
        include:
          # Test features
          - task: test
            rust: stable
            target: x86_64-unknown-linux-gnu
            features: "''"
          - task: test
            rust: stable
            target: x86_64-unknown-linux-gnu
            features: serde
          - task: test
            rust: stable
            target: x86_64-unknown-linux-gnu
            features: time
          - task: test
            rust: stable
            target: x86_64-unknown-linux-gnu
            features: chrono
          - task: test
            rust: stable
            target: x86_64-unknown-linux-gnu
            features: all
          - task: test
            rust: stable
            target: x86_64-unknown-linux-gnu
            features: default

          # Test targets
          - task: test
            rust: stable
            target: i686-unknown-linux-gnu
            features: default
          - task: test
            rust: stable
            target: x86_64-unknown-linux-gnu
            features: default
          # - task: test
          #   rust: stable
          #   target: arm-unknown-linux-gnueabihf
          #   features: default
          #   test_args: --no-run
          # - task: test
          #   rust: stable
          #   target: armv7-unknown-linux-gnueabihf
          #   features: default
          #   test_args: --no-run
          # - task: test
          #   rust: stable
          #   target: aarch64-unknown-linux-gnu
          #   features: default
          #   test_args: --no-run
          # - task: test
          #   rust: stable
          #   target: powerpc64-unknown-linux-gnu
          #   features: default
          #   test_args: --no-run

          # Test channels
          - task: channels
            rust: stable
            target: x86_64-unknown-linux-gnu
            features: default
          - task: channels
            rust: beta
            target: x86_64-unknown-linux-gnu
            features: default
          - task: channels
            rust: nightly
            target: x86_64-unknown-linux-gnu
            features: default

    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup cross linux toolchain
        if: contains(matrix.target, '-linux-') && !startsWith(matrix.target, 'x86_64-')
        run: |
          GCC_TARGET=$(printf "${{ matrix.target }}" | sed 's/-unknown-/-/' | sed 's/arm[^-]*/arm/g')
          PKG_TARGET=$(printf "${{ matrix.target }}" | sed 's/-unknown-.*$//' | sed 's/i686/i386/g' | sed 's/arm[^-]*/armhf/g' | sed 's/aarch64/arm64/g' | sed 's/powerpc64/ppc64el/g')
          ENV_TARGET=$(printf "${{ matrix.target }}" | tr '-' '_')
          ENV_TARGET_UC=$(printf "${ENV_TARGET}" | tr '[[:lower:]]' '[[:upper:]]')
          sudo dpkg --add-architecture ${PKG_TARGET}
          PKG_DIST=$(cat /etc/os-release | grep '^VERSION_CODENAME=' | sed 's/VERSION_CODENAME=//g')
          cat /etc/apt/sources.list
          cat /etc/apt/apt-mirrors.txt
          ls -al /etc/apt/sources.list.d
          cat /etc/apt/sources.list.d/*
          if [ "${PKG_TARGET}" == "i386" ]; then
            PKG_REPO="http://us.archive.ubuntu.com/ubuntu/"
          else
            PKG_REPO="http://ports.ubuntu.com/ubuntu-ports/"
            sudo sed -i 's/deb mirror/deb [arch=amd64] mirror/g' /etc/apt/sources.list
          fi
          echo "deb [arch=${PKG_TARGET}] ${PKG_REPO} ${PKG_DIST} main" | sudo tee /etc/apt/sources.list.d/cross.list
          sudo apt-get update -y
          sudo apt-get install -y --install-recommends crossbuild-essential-${PKG_TARGET} pkg-config-${GCC_TARGET} libdbus-1-dev:${PKG_TARGET}
          echo "PKG_CONFIG_${ENV_TARGET}=${GCC_TARGET}-pkg-config" >> $GITHUB_ENV
          echo "CC_${ENV_TARGET}=${GCC_TARGET}-gcc" >> $GITHUB_ENV
          echo "CARGO_TARGET_${ENV_TARGET_UC}_LINKER=${GCC_TARGET}-gcc" >> $GITHUB_ENV
          #echo "PKG_CONFIG_ALLOW_CROSS=1" >> $GITHUB_ENV
      - name: Install system dependencies
        if: contains(matrix.target, '-linux-') && startsWith(matrix.target, 'x86_64-')
        run: |
          sudo apt-get update -y
          sudo apt-get install -y --install-recommends libdbus-1-dev
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          target: ${{ matrix.target }}
      - uses: Swatinem/rust-cache@v2
      - name: Update deps
        run: cargo update
      - name: Build
        run: cargo build --target ${{ matrix.target }} --no-default-features --features ${{ matrix.features }}
      - name: Test
        timeout-minutes: 2
        env:
          RUST_BACKTRACE: full
        run: cargo test --all --target ${{ matrix.target }} --no-default-features --features ${{ matrix.features }} ${{ matrix.test_args }}

  publish:
    if: github.repository == 'katyo/bluetooth-ots-rs' && startsWith(github.ref, 'refs/tags/')
    needs:
      - test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
      - name: Publish crates
        uses: katyo/publish-crates@v1
        with:
          registry-token: ${{ secrets.CRATES_TOKEN }}
          args: --no-verify
          #dry-run: true
